CREATE TABLE mytable(
   ID                   INTEGER  NOT NULL PRIMARY KEY 
  ,Growing_Zone         INTEGER  NOT NULL
  ,Tree_name            VARCHAR(30) NOT NULL
  ,Botanical_Name       VARCHAR(45) NOT NULL
  ,Tree_Images          VARCHAR(56)
  ,Overview_Description VARCHAR(4) NOT NULL
  ,Sun_Preference       VARCHAR(23) NOT NULL
  ,Soil_Preference      VARCHAR(16) NOT NULL
  ,Mature_Height        VARCHAR(12) NOT NULL
  ,Mature_Spread        VARCHAR(12) NOT NULL
  ,Growth_Speed         VARCHAR(6) NOT NULL
  ,Flower_Color         VARCHAR(11) NOT NULL
  ,Foliage_Color        VARCHAR(11) NOT NULL
  ,Fall_Color           VARCHAR(30) NOT NULL
  ,Pollinator_Friendly  VARCHAR(3) NOT NULL
  ,Outgoing_Link        VARCHAR(58) NOT NULL
);
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (1,4,'Jane Magnolia Tree','Magnolia x ''Jane''','Store in database?  Or reference NatureHills.com photos?','????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (2,5,'Jane Magnolia Tree','Magnolia x ''Jane''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (3,6,'Jane Magnolia Tree','Magnolia x ''Jane''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (4,7,'Jane Magnolia Tree','Magnolia x ''Jane''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (5,8,'Jane Magnolia Tree','Magnolia x ''Jane''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (6,5,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (7,6,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (8,7,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (9,8,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (10,9,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (11,2,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (12,3,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (13,4,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (14,5,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (15,6,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (16,7,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (17,6,'Okame Cherry Tree','Prunus x ''Okame''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','15 - 30 Feet','20 - 30 Feet','Medium','Pink','Green','Yellow, Orange, Red','Yes','https://www.naturehills.com/okame-cherry');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (18,7,'Okame Cherry Tree','Prunus x ''Okame''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','15 - 30 Feet','20 - 30 Feet','Medium','Pink','Green','Yellow, Orange, Red','Yes','https://www.naturehills.com/okame-cherry');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (19,8,'Okame Cherry Tree','Prunus x ''Okame''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','15 - 30 Feet','20 - 30 Feet','Medium','Pink','Green','Yellow, Orange, Red','Yes','https://www.naturehills.com/okame-cherry');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (20,2,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (21,3,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (22,4,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (23,5,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (24,6,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (25,4,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (26,5,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (27,6,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (28,7,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (29,8,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (30,3,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (31,4,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (32,5,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (33,6,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (34,7,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (35,8,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (36,9,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (37,6,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (38,7,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (39,8,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (40,9,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (41,10,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (42,4,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (43,5,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (44,6,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (45,7,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (46,8,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (47,9,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (48,3,'Rocky Mountain Juniper','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (49,4,'Rocky Mountain Juniper','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (50,5,'Rocky Mountain Juniper','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (51,6,'Rocky Mountain Juniper','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (52,7,'Autumn Brilliance Serviceberry','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (53,3,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (54,4,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (55,5,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (56,6,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (57,7,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (58,8,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO mytable(ID,Growing_Zone,Tree_name,Botanical_Name,Tree_Images,Overview_Description,Sun_Preference,Soil_Preference,Mature_Height,Mature_Spread,Growth_Speed,Flower_Color,Foliage_Color,Fall_Color,Pollinator_Friendly,Outgoing_Link) VALUES (59,9,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
