CREATE TABLE treesTable(
   ID                   INTEGER  NOT NULL PRIMARY KEY 
  ,growing_zone         INTEGER  NOT NULL  
  ,tree_name            VARCHAR(0) NOT NULL
  ,botapical_name       VARCHAR(5) NOT NULL
  ,tree_images          VARCHAR(56) 
  ,Overview_descpiption VARCHAR(4) NoT NULL
  ,sun_preference       VARCHAR(23) NOT NULL
  ,soil_preference      VARCHAR(16) NOT NULL
  ,mature_height        VARCHAR(12) NOT NULL
  ,mature_spread        VARCHAR(12) NOT NULL
  ,growth_speed         VARCHAR(6) NOT NULL
  ,flower_color         VARCHAR(11) NOT NULL
  ,foliage_color        VARCHAR(11) NOT NULL
  ,fall_color           VARCHAR(30) NOT NULL
  ,pollinator_friendly  VARCHAR(3) NOT NULL
  ,outgoing_link        VARCHAR(58) NOT NULL
);
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (1,4,'Jane Magnolia Tree','Magnolia x ''Jane''','Store in database?  Or reference NatureHills.com photos?','????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (2,5,'Jane Magnolia Tree','Magnolia x ''Jane''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (3,6,'Jane Magnolia Tree','Magnolia x ''Jane''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (4,7,'Jane Magnolia Tree','Magnolia x ''Jane''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (5,8,'Jane Magnolia Tree','Magnolia x ''Jane''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','8 - 10 Feet','Medium','Pink, White','Green','Orange','Yes','https://www.naturehills.com/magnolia-x-jane');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (6,5,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (7,6,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (8,7,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (9,8,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (10,9,'Blue Chinese Wisteria Tree','Wisteria sinensis',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','10 - 15 Feet','10 - 12 Feet','Fast','Blue','Green','Yellow','Yes','https://www.naturehills.com/blue-chinese-wisteria');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (11,2,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (12,3,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (13,4,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (14,5,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (15,6,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (16,7,'Colorado Spruce','Picea pungens',NULL,'????','Full Sun, Partial Shade','Well Drained','50 - 60 Feet','12 - 20 Feet','Slow','N/A','Green, Blue','Evergreen','No','https://www.naturehills.com/colorado-spruce');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (17,6,'Okame Cherry Tree','Prunus x ''Okame''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','15 - 30 Feet','20 - 30 Feet','Medium','Pink','Green','Yellow, Orange, Red','Yes','https://www.naturehills.com/okame-cherry');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (18,7,'Okame Cherry Tree','Prunus x ''Okame''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','15 - 30 Feet','20 - 30 Feet','Medium','Pink','Green','Yellow, Orange, Red','Yes','https://www.naturehills.com/okame-cherry');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (19,8,'Okame Cherry Tree','Prunus x ''Okame''',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','15 - 30 Feet','20 - 30 Feet','Medium','Pink','Green','Yellow, Orange, Red','Yes','https://www.naturehills.com/okame-cherry');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (20,2,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (21,3,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (22,4,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (23,5,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (24,6,'Quaking Aspen Tree','Populus Tremuloides ''Quaking''',NULL,'????','Full Sun','Widely Adaptable','40 - 50 Feet','20 - 30 Feet','Fast','N/A','Dark Green','Yellow','Yes','https://www.naturehills.com/aspen-quaking');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (25,4,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (26,5,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (27,6,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (28,7,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (29,8,'Autumn Blaze Maple','Acer x freemanii ''Jeffersred''',NULL,'????','Full Sun','Widely Adaptable','40 - 60 Feet','40 - 60 Feet','Fast','Red','Green','Red','Yes','https://www.naturehills.com/autumn-blaze-red-maple');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (30,3,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (31,4,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (32,5,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (33,6,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (34,7,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (35,8,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (36,9,'Eastern Red Cedar','Juniperus virginiana',NULL,'????','Full Sun, Partial Shade','Widely Adaptable','40 - 60 Feet','10 - 20 Feet','Medium','N/A','Green','Evergreen','No','https://www.naturehills.com/eastern-red-cedar');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (37,6,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (38,7,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (39,8,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (40,9,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (41,10,'Mimosa Tree','Albizia julibrissin ''Rosea''','???','???','Full Sun','Widely Adaptable','20 - 35 feet','25 - 30 feet','Fast','Light Pink','Green','N/A','Yes','https://www.naturehills.com/mimosa-tree');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (42,4,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (43,5,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (44,6,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (45,7,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (46,8,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (47,9,'Aristocrat Flowering Pear Tree','Pyrus calleryana ''Aristocrat''','???','???','Full Sun','Widely Adaptable','25 - 40 feet','20 - 30 feet','Fast','White','Green','Yellow, Red, Burgundy / Purple','Yes','https://www.naturehills.com/aristocrat-flowering-pear');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (48,3,'Rocky Mountain Juniper','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (49,4,'Rocky Mountain Juniper','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (50,5,'Rocky Mountain Juniper','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (51,6,'Rocky Mountain Juniper','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (52,7,'Autumn Brilliance Serviceberry','Juniperus scopulorm','???','???','Full Sun','Well Drained','30 - 40 feet','6 - 10 feet','Slow','Evergreen','Blue Green','Evergreen','No','https://www.naturehills.com/rocky-mountain-juniper');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (53,3,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (54,4,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (55,5,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (56,6,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (57,7,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (58,8,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
INSERT INTO treesTable(ID,growing_zone,tree_name,botanical_name,tree_images,overview_description,sun_preference,soil_preference,mature_height,mature_spread,growth_speed,flower_color,foliage_color,fall_color,pollinator_friendly,outgoing_link) VALUES (59,9,'Autumn Brilliance Serviceberry','Amelanchier x grandiflora ''Autumn Brilliance''','???','???','Full Sun, Partial Shade','Well Drained','20 - 25 feet','15 - 20 feet','Medium','White','Blue-Green','Orange, Red','Yes','https://www.naturehills.com/autumn-brilliance-serviceberry');
